"""adds FK between user and role

Revision ID: 258cc29c1ee6
Revises: 3978fdde9f7b
Create Date: 2021-07-20 10:00:34.105628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258cc29c1ee6'
down_revision = '3978fdde9f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
